package by.andersen.amnbanking.utils;

import by.andersen.amnbanking.data.AlertAPI;
import by.andersen.amnbanking.data.SmsVerificationData;
import by.andersen.amnbanking.data.UsersData;
import org.testng.annotations.DataProvider;

import static org.apache.hc.core5.http.HttpStatus.SC_BAD_REQUEST;
import static org.apache.hc.core5.http.HttpStatus.SC_UNPROCESSABLE_ENTITY;

public class DataProviderTests {
    @DataProvider(name = "User's registration with valid data")
    public static Object[][] inputForUserRegistrationWithValidData() {
        return new Object[][]{
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber()},
                {UsersData.EM79_VALID_PASS.getUser().getLogin(),
                        UsersData.EM79_VALID_PASS.getUser().getPassword(),
                        UsersData.EM79_VALID_PASS.getUser().getPassport(),
                        UsersData.EM79_VALID_PASS.getUser().getPhoneNumber()},
                {UsersData.EM79_VALID_PASS_DIGITS.getUser().getLogin(),
                        UsersData.EM79_VALID_PASS_DIGITS.getUser().getPassword(),
                        UsersData.EM79_VALID_PASS_DIGITS.getUser().getPassport(),
                        UsersData.EM79_VALID_PASS_DIGITS.getUser().getPhoneNumber()},
                {UsersData.EM79_VAL_PASS_2NUMBERS.getUser().getLogin(),
                        UsersData.EM79_VAL_PASS_2NUMBERS.getUser().getPassword(),
                        UsersData.EM79_VAL_PASS_2NUMBERS.getUser().getPassport(),
                        UsersData.EM79_VAL_PASS_2NUMBERS.getUser().getPhoneNumber()},
                {UsersData.EM79_MAX_SYM_PASS.getUser().getLogin(),
                        UsersData.EM79_MAX_SYM_PASS.getUser().getPassword(),
                        UsersData.EM79_MAX_SYM_PASS.getUser().getPassport(),
                        UsersData.EM79_MAX_SYM_PASS.getUser().getPhoneNumber()},
                {UsersData.EM79_MIN_CHARS_PHONE.getUser().getLogin(),
                        UsersData.EM79_MIN_CHARS_PHONE.getUser().getPassword(),
                        UsersData.EM79_MIN_CHARS_PHONE.getUser().getPassport(),
                        UsersData.EM79_MIN_CHARS_PHONE.getUser().getPhoneNumber()},
                {UsersData.EM79_MAX_CHARS_PHONE.getUser().getLogin(),
                        UsersData.EM79_MAX_CHARS_PHONE.getUser().getPassword(),
                        UsersData.EM79_MAX_CHARS_PHONE.getUser().getPassport(),
                        UsersData.EM79_MAX_CHARS_PHONE.getUser().getPhoneNumber()}

        };
    }

    @DataProvider(name = "User's registration with invalid passport field data")
    public static Object[][] inputForUserRegistrationWithInValidPassportField() {
        return new Object[][]{
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        "11236489235FR456871232.",
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PASSPORT.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        "мн88954232156",
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PASSPORT.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        "AM4567",
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_UNPROCESSABLE_ENTITY,
                        "User with passport = AM4567 already registered"},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        "КВ88954232156",
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PASSPORT.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        "MN88954232156 ",
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PASSPORT.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        "mn88954232156",
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PASSPORT.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        "P",
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PASSPORT.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        "PL45873698710254D78519F12547862",
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PASSPORT.getValue()},
        };
    }

    @DataProvider(name = "User's registration with invalid login field data")
    public static Object[][] inputForUserRegistrationWithInValidLoginField() {
        return new Object[][]{
                {"11122222222222233333",
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_UNPROCESSABLE_ENTITY,
                        "User with login = 11122222222222233333 already registered"},
                {"22233333333333333333",
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {"Eminem79а",
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {"111впрТЫ",
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {"111CDV",
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {"111111111111111111111Pv",
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {" 111*?/)! ;",
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {"",
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
        };
    }

    @DataProvider(name = "User's registration with invalid password field data")
    public static Object[][] inputForUserRegistrationWithInValidPasswordField() {
        return new Object[][]{
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        "11122222222222233333",
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        "1111111111222222ваТЫ",
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        "111111",
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        "111111111111111111111",
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        "",
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        "aaaaaaaaAA",
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER.getValue()},
        };
    }

    @DataProvider(name = "User's registration with invalid phone field data")
    public static Object[][] inputForUserRegistrationWithInValidPhoneField() {
        return new Object[][]{
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+375555555555",
                        SC_UNPROCESSABLE_ENTITY,
                        "User with phone = +375555555555 already registered"},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+375235555555 ",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "375235555555 ",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        " +375235555555",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+375235555555.",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+375235555555*",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+375235555555+",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+375235555555,",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+            ",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "             ",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+2056487951",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+3620547894563201",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+mmmmmmmmmmm",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+LLLLLLLLLLLL",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        "+920215h456",
                        SC_BAD_REQUEST,
                        AlertAPI.REGISTRATION_FAILED_USER_PHONE.getValue()},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPassport(),
                        SC_BAD_REQUEST,
                        "Phone cannot be null"},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        UsersData.USER_EMINEM79.getUser().getPhoneNumber(),
                        SC_BAD_REQUEST,
                        "Passport cannot be null"},
        };
    }

    @DataProvider(name = "ChangePasswordAfter1LoginInvalidPass")
    public static Object[][] changePasswordAfter1LoginUserInvalidPass() {
        return new Object[][]{
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        SmsVerificationData.SMS_VALID.getValue(),
                        "Num1"},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        SmsVerificationData.SMS_VALID.getValue(),
                        "NumLcndvS"},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        SmsVerificationData.SMS_VALID.getValue(),
                        "569102561"},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        SmsVerificationData.SMS_VALID.getValue(),
                        "5691Lvd."},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        SmsVerificationData.SMS_VALID.getValue(), ""},
                {UsersData.USER_EMINEM79.getUser().getLogin(),
                        UsersData.USER_EMINEM79.getUser().getPassword(),
                        SmsVerificationData.SMS_VALID.getValue(), "Number1 "}
        };
    }
}

