# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages
image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

stages:  
  - build
  - test
  - package
  - notify

build:
  stage: build
  only:
    - master
    - merge_requests
    - /^release\/.*$/
  except:
    - tags
  script:
    - 'mvn compile'
  cache:
    paths:
      - ./target
      - ./.m2

test:
  stage: test
  only:
    - dev
    - merge_requests
    - /^release\/.*$/
  except:
    - tags
  script:
    - 'mvn test'
  cache:
    paths:
      - ./target
      - ./.m2

package:
  stage: package
  only:
    - dev
    - /^release\/.*$/
  except:
    - tags
  script:
    - 'mvn package -Dmaven.test.skip=true'
  artifacts:
    paths:
      - target/*.jar
  cache:
    policy: pull
    paths:
      - ./target
      - ./.m2

notify_error:
  stage: notify
  only:
    - master
    - /^release\/.*$/
  script:
    - sh ci-notify.sh 
  when: on_failure

notify_error_release:
  stage: notify
  only:
    - /^release-.*$/
  except:
    - branches
  script:
    - sh ci-notify.sh 
  when: on_failure