# For more information, see: https://docs.gitlab.com/ee/ci/yaml/README.html#stages
image: openjdk:11-jdk-slim

stages:  
  - build
  - test

build:
  stage: build
  only:
    - master
  script:
    - mvn compile

test:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - mvn test